# Generated by Django 4.2.6 on 2024-03-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default=1, upload_to='topic_images'),
        ),
    ]
