# Generated by Django 4.2.6 on 2024-04-14 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_imagecaption'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imagecaption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.imagecaption'),
        ),
        migrations.AlterField(
            model_name='imagecaption',
            name='caption',
            field=models.CharField(default='No caption created', max_length=255),
        ),
    ]
