# Generated by Django 4.2.6 on 2024-04-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_imagecaption_alter_imagecaption_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='imagecaption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.imagecaption'),
        ),
    ]
