# Generated by Django 4.2.6 on 2024-04-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_topic_imagecaption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='weight',
        ),
    ]
